<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>LocalChromeStore</AssemblyName>
    <RootNamespace>LocalChromeStore</RootNamespace>
    <Version>0.3.5</Version>
    <FileVersion>0.3.5.0</FileVersion>
    <AssemblyVersion>0.3.5.0</AssemblyVersion>
    <Product>LocalChromeStore</Product>
    <Company>SysAdminDoc</Company>
    <Copyright>Copyright (c) 2026 SysAdminDoc. MIT License.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Octokit" Version="13.0.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.0" />
  </ItemGroup>

</Project>
